/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package compliance;

import java.util.Properties;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author hohkim
 */
public final class IndexOpenDialog extends javax.swing.JDialog {

    Companion companion;
    Properties properties;
    /**
     * Creates new form IndexOpenDialog
     */
    public IndexOpenDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        companion = (Companion) parent;
        initComponents();
        initFields();
    }

    public void initFields() {
        properties = companion.propManager.properties;
        indexLbl.setText(properties.getProperty("indexDir"));
        
        switch (properties.getProperty("language")) {
            case "Korean" : languageCmb.setSelectedIndex(0); break;
            case "English" : languageCmb.setSelectedIndex(1); break;
            case "Japanese" : languageCmb.setSelectedIndex(2); break;                
            case "Chinese" : languageCmb.setSelectedIndex(3); break;                
        }
        
        int pageSize = Integer.parseInt(properties.getProperty("countPerPage"));
        switch (pageSize) {
            case 10 : pageSizeCmb.setSelectedIndex(0); break;
            case 20 : pageSizeCmb.setSelectedIndex(1); break;                
            case 30 : pageSizeCmb.setSelectedIndex(2); break;
            case 40 : pageSizeCmb.setSelectedIndex(3); break;    
            case 50 : pageSizeCmb.setSelectedIndex(4); break;                
            case 100 : pageSizeCmb.setSelectedIndex(5); break;
            case 1000 : pageSizeCmb.setSelectedIndex(6); break;                
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        indexBtn = new javax.swing.JButton();
        languageCmb = new javax.swing.JComboBox();
        label3 = new javax.swing.JLabel();
        okBtn = new javax.swing.JButton();
        indexLbl = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        cancelBtn = new javax.swing.JButton();
        label4 = new javax.swing.JLabel();
        pageSizeCmb = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        indexBtn.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        indexBtn.setText("Index Directory");
        indexBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                indexBtnActionPerformed(evt);
            }
        });

        languageCmb.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        languageCmb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Korean", "English", "Japanese", "Chinese", " " }));

        label3.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        label3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label3.setText("[ Searcher 설정 ]");

        okBtn.setText("OK");
        okBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBtnActionPerformed(evt);
            }
        });

        indexLbl.setText("좌측 버튼을 눌러 선택해주세요.");

        label2.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        label2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label2.setText("Index 작성 시 언어");
        label2.setToolTipText("");
        label2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        label4.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        label4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label4.setText("Page 당 조회 건수");
        label4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        pageSizeCmb.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        pageSizeCmb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "10", "20", "30", "40", "50", "100", "1000" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(cancelBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(okBtn))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(label4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(label2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(indexBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(indexLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE)
                                    .addComponent(languageCmb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(pageSizeCmb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(39, 39, 39))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(label3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(indexBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(indexLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label2)
                    .addComponent(languageCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label4)
                    .addComponent(pageSizeCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelBtn)
                    .addComponent(okBtn))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void indexBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_indexBtnActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new java.io.File(indexLbl.getText()));
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        chooser.setAcceptAllFileFilterUsed(false);
        
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) { 
            indexLbl.setText(chooser.getSelectedFile().getAbsolutePath());
        } 
    }//GEN-LAST:event_indexBtnActionPerformed

    private void okBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBtnActionPerformed
        String indexDir = indexLbl.getText();    
        companion.setIndexDir(indexDir);
        properties.setProperty("indexDir", indexDir);
        
        String language = (String) languageCmb.getSelectedItem();
        switch (language) {
            case "0" : 
                properties.setProperty("languase", "Korean"); 
                break;
            case "1" :
                properties.setProperty("languase", "English"); 
                break;    
            case "2" : 
                properties.setProperty("languase", "Japanese"); 
                break;
            case "3" :
                properties.setProperty("languase", "Chinese"); 
                break;                    
        }
        
        String pageSize = (String) pageSizeCmb.getSelectedItem();
        properties.setProperty("countPerPage", pageSize);

        companion.setNavigateButtonsDisable();
        companion.setEnableSearchButton();
        companion.setEnableKeywordLoadButton();
        companion.setEnableKeywordSaveButton();
        companion.resultTableColumnWidthAdjust();
        
        companion.searcher.setIndexDir(indexDir);
        companion.searcher.setAnalyzer(language);
        companion.searcher.setPageSize(Integer.parseInt(pageSize));
        companion.setIndexInfolabel(String.format("%s (%s Analyzer)", indexDir, language));
        companion.searcher.initSearcher();
        this.dispose();
    }//GEN-LAST:event_okBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IndexOpenDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IndexOpenDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IndexOpenDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IndexOpenDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                IndexOpenDialog dialog = new IndexOpenDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton indexBtn;
    private javax.swing.JLabel indexLbl;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    private javax.swing.JComboBox languageCmb;
    private javax.swing.JButton okBtn;
    private javax.swing.JComboBox pageSizeCmb;
    // End of variables declaration//GEN-END:variables
}
