/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package compliance;

import compliance.AuditCompanion.DocLang;
import java.awt.Desktop;
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.TableColumn;
import javax.swing.table.TableModel;
import org.apache.lucene.analysis.Analyzer;
import org.apache.lucene.analysis.ja.JapaneseAnalyzer;
import org.apache.lucene.analysis.kr.KoreanAnalyzer;
import org.apache.lucene.analysis.standard.StandardAnalyzer;
import org.apache.lucene.document.Document;
import org.apache.lucene.index.CorruptIndexException;
import org.apache.lucene.index.IndexReader;
import org.apache.lucene.queryParser.ParseException;
import org.apache.lucene.queryParser.QueryParser;
import org.apache.lucene.search.IndexSearcher;
import org.apache.lucene.search.Query;
import org.apache.lucene.search.ScoreDoc;
import org.apache.lucene.search.TopDocs;
import org.apache.lucene.store.FSDirectory;
import org.apache.lucene.util.Version;
/**
 *
 * @author hohkim
 */
public class Searcher extends javax.swing.JFrame {

    final static String OFFICE_PROGRAM_DIR = "C:\\Program Files (x86)\\Microsoft Office\\Office14";
    private String queryString;
    private String indexDir;
    private Page page;
    private MyTableModel model;
    private IndexReader reader;
    private IndexSearcher searcher;
    private Analyzer analyzer;
    private TopDocs topDocs;
    private Query query;
    
    /**
     * Creates new form Searcher
     */
    public Searcher(String indexDir, DocLang docLang) throws IOException {
        this.indexDir = indexDir;
        initComponents();
        setExtendedState(this.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        hSplitPane.setDividerLocation(300);
        
        // IndexSearcher
        reader = IndexReader.open(FSDirectory.open(new File(this.indexDir)));
        searcher = new IndexSearcher(reader);
        // Analizer
        if (docLang == DocLang.English) {
            analyzer = new StandardAnalyzer(Version.LUCENE_36);
        } else if (docLang == DocLang.Korean) {
            try {
                analyzer = new KoreanAnalyzer(Version.LUCENE_36);
            } catch (IOException ex) {
               System.out.println(ex);
            }
        } else if (docLang == DocLang.Japanease) {
            analyzer = new JapaneseAnalyzer(Version.LUCENE_36);
        }        
        // Page initialize
        page = new Page(1);
        page.setPageSize(5);
        //this.setIconImage(new ImageIcon("D:\\Software\\Icons\\audits.jpg").getImage());
        setNavigateButtonsDisable();       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        upperP = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        searchWords = new javax.swing.JTextArea();
        searchBotton = new javax.swing.JButton();
        midP = new javax.swing.JPanel();
        hSplitPane = new javax.swing.JSplitPane();
        midLeftPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultTable = new javax.swing.JTable();
        midLeftBottomP = new javax.swing.JPanel();
        firstButton = new javax.swing.JButton();
        beforeButton = new javax.swing.JButton();
        nextButton = new javax.swing.JButton();
        lastButton = new javax.swing.JButton();
        pageText = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        pageLabel = new javax.swing.JLabel();
        tabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        contentsArea = new javax.swing.JEditorPane();
        bottomP = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        setPreferredSize(new java.awt.Dimension(1024, 768));

        mainPanel.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("맑은 고딕", 1, 12)); // NOI18N
        jLabel2.setText("검색어");

        searchWords.setColumns(20);
        searchWords.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        searchWords.setRows(5);
        jScrollPane2.setViewportView(searchWords);

        searchBotton.setText("Go");
        searchBotton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBottonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout upperPLayout = new javax.swing.GroupLayout(upperP);
        upperP.setLayout(upperPLayout);
        upperPLayout.setHorizontalGroup(
            upperPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, upperPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(upperPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addGroup(upperPLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1007, Short.MAX_VALUE)
                        .addComponent(searchBotton)))
                .addContainerGap())
        );
        upperPLayout.setVerticalGroup(
            upperPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(upperPLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(upperPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(searchBotton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))
        );

        mainPanel.add(upperP, java.awt.BorderLayout.PAGE_START);

        hSplitPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        hSplitPane.setDividerLocation(300);

        midLeftPanel.setLayout(new java.awt.BorderLayout());

        resultTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        resultTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        resultTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resultTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(resultTable);

        midLeftPanel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        firstButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/compliance/images/first.jpg"))); // NOI18N
        firstButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        firstButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/compliance/images/first.jpg"))); // NOI18N
        firstButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstButtonActionPerformed(evt);
            }
        });

        beforeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/compliance/images/back.jpg"))); // NOI18N
        beforeButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51)));
        beforeButton.setMaximumSize(new java.awt.Dimension(77, 57));
        beforeButton.setMinimumSize(new java.awt.Dimension(77, 57));
        beforeButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/compliance/images/back.jpg"))); // NOI18N
        beforeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beforeButtonActionPerformed(evt);
            }
        });

        nextButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/compliance/images/foward.jpg"))); // NOI18N
        nextButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51)));
        nextButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/compliance/images/foward.jpg"))); // NOI18N
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        lastButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/compliance/images/last.jpg"))); // NOI18N
        lastButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        lastButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/compliance/images/last.jpg"))); // NOI18N
        lastButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastButtonActionPerformed(evt);
            }
        });

        pageText.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        pageText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pageText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pageTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout midLeftBottomPLayout = new javax.swing.GroupLayout(midLeftBottomP);
        midLeftBottomP.setLayout(midLeftBottomPLayout);
        midLeftBottomPLayout.setHorizontalGroup(
            midLeftBottomPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(midLeftBottomPLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(firstButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(beforeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lastButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pageText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(176, Short.MAX_VALUE))
        );
        midLeftBottomPLayout.setVerticalGroup(
            midLeftBottomPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, midLeftBottomPLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(midLeftBottomPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(firstButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pageText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(beforeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        midLeftPanel.add(midLeftBottomP, java.awt.BorderLayout.PAGE_END);

        pageLabel.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        pageLabel.setText("Page:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pageLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        midLeftPanel.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        hSplitPane.setLeftComponent(midLeftPanel);

        tabbedPane1.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N

        contentsArea.setContentType("text/html"); // NOI18N
        jScrollPane3.setViewportView(contentsArea);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
        );

        tabbedPane1.addTab("Contents", jPanel1);

        hSplitPane.setRightComponent(tabbedPane1);

        javax.swing.GroupLayout midPLayout = new javax.swing.GroupLayout(midP);
        midP.setLayout(midPLayout);
        midPLayout.setHorizontalGroup(
            midPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(midPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1092, Short.MAX_VALUE)
                .addContainerGap())
        );
        midPLayout.setVerticalGroup(
            midPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(midPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hSplitPane)
                .addContainerGap())
        );

        mainPanel.add(midP, java.awt.BorderLayout.CENTER);

        bottomP.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Powered by Lucene");
        bottomP.add(jLabel1, java.awt.BorderLayout.CENTER);

        mainPanel.add(bottomP, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchBottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBottonActionPerformed
        // TODO add your handling code here:
        page.setCurrentPageNo(1);
        queryString = searchWords.getText();
        try {
            search();
        } catch (Exception ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_searchBottonActionPerformed

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        page.setCurrentPageNo(page.getCurrentPageNo()+1);
        try {
            search();
        } catch (IOException ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_nextButtonActionPerformed

    private void beforeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beforeButtonActionPerformed
       page.setCurrentPageNo(page.getCurrentPageNo()-1);
        try {
            search();
        } catch (IOException ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_beforeButtonActionPerformed

    private void firstButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstButtonActionPerformed
       page.setCurrentPageNo(1);
        try {
            search();
        } catch (IOException ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_firstButtonActionPerformed

    private void lastButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastButtonActionPerformed
        page.setCurrentPageNo(page.getPageCount());
        try {
            search();
        } catch (IOException ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_lastButtonActionPerformed

    private void pageTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pageTextActionPerformed
        int pageNo = page.getCurrentPageNo();
        try {
            pageNo = Integer.parseInt(pageText.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please input numbers.", "Numeric Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (pageNo < 1 || pageNo > page.getPageCount()) {
            JOptionPane.showMessageDialog(null, "Page range is out of bound.", "Page No Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        page.setCurrentPageNo(pageNo);
        try {
            search();
        } catch (IOException ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_pageTextActionPerformed

    private void resultTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resultTableMouseClicked
        int row = resultTable.getSelectedRow();
        int id = (int) model.getValueAt(row, 0);
        if (evt.getClickCount() == 1) {
            // contents display
            ScoreDoc scoreDoc = topDocs.scoreDocs[id - 1];
            Document d;
            try {
                d = searcher.doc(scoreDoc.doc);
                String contents = d.get("contents");
                String[] fragments = MyUtil.getFragmentsWithHighlightedTerms(analyzer, query, "contents", contents, 100, 100);
                String highlighted = "";
                for (String frag : fragments) {
                    highlighted += frag;
                }
                contentsArea.setText(highlighted.replaceAll("\n", "<br/>"));
            } catch (CorruptIndexException ex) {
                System.out.println(ex);
            } catch (IOException ex) {
                System.out.println(ex);
            }
            contentsArea.setCaretPosition(0);
        } else if (evt.getClickCount() == 2) {
            // Open external program
            String docDir = indexDir.replace("Index", "Files");
            String fn = (String) model.getValueAt(row, 1);
            File file = new File(docDir, fn);
            try {
                Desktop.getDesktop().open(file);
            } catch (IOException ex) {
                System.out.println(ex);
            }
        }
    }//GEN-LAST:event_resultTableMouseClicked

    public void search () throws IOException {
        QueryParser parser = new QueryParser(Version.LUCENE_36, "contents", analyzer);
        try {
            query = parser.parse(queryString);
        } catch (ParseException ex) {
            System.out.println(ex);
        }
        
        //TopDocs docs = null;
        try {
            topDocs = searcher.search(query, page.getEnd());
        } catch (IOException ex) {
            Logger.getLogger(Searcher.class.getName()).log(Level.SEVERE, null, ex);
        }
        page.setTotalCount(topDocs.totalHits);
        System.out.format("Total hits: %d, Total Page: %d\n",
                topDocs.totalHits, page.getPageCount());

        System.out.println("Current page: " + page.getCurrentPageNo());
        // for tablemodel
        Object[][] data = new Object[page.getPageSize()][2];
        String[] columnNames = {"SQ", "File Name" };
        for (int i = page.getStart(); i < page.getEnd(); i++) {
            ScoreDoc scoreDoc = topDocs.scoreDocs[i];
            Document d = searcher.doc(scoreDoc.doc);
            System.out.format(" %3d. (%.5f) %s\n", i + 1, scoreDoc.score, d.get("filename"));
            //contents.append(String.format(" %3d. (%.5f) %s\n", i + 1, scoreDoc.score, d.get("filename")));
            data[i-page.getStart()][0] = i+1;
            data[i-page.getStart()][1] = d.get("filename");
        }
        pageLabel.setText(String.format("Page: %d/%d, (Total Hits: %d)", 
                page.getCurrentPageNo(), page.getPageCount(), page.getTotalCount()));
        model = new MyTableModel(data, columnNames);
        resultTable.setModel(model);
        resultTableColumnWidthAdjust();
        setNavigateButtonsState();
	}
    
    public void initResultTable() {
        Object[][] data = { {"", "" } };
        String[] columnNames = {"SQ", "File Name" };
        model = new MyTableModel(data, columnNames);
        resultTable.setModel(model);
        resultTableColumnWidthAdjust();
    }
    
    public void resultTableColumnWidthAdjust () {
        resultTable.getColumnModel().getColumn(0).setMaxWidth(40);
        resultTable.getColumnModel().getColumn(1).setMinWidth(100);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Searcher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Searcher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Searcher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Searcher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    Searcher searcher = new Searcher("F:\\Binder\\Index", DocLang.Korean);
                    searcher.initResultTable();
                    searcher.setVisible(true);
                } catch (IOException ex) {
                    System.out.println(ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton beforeButton;
    private javax.swing.JPanel bottomP;
    private javax.swing.JEditorPane contentsArea;
    private javax.swing.JButton firstButton;
    private javax.swing.JSplitPane hSplitPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton lastButton;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel midLeftBottomP;
    private javax.swing.JPanel midLeftPanel;
    private javax.swing.JPanel midP;
    private javax.swing.JButton nextButton;
    private javax.swing.JLabel pageLabel;
    private javax.swing.JTextField pageText;
    private javax.swing.JTable resultTable;
    private javax.swing.JButton searchBotton;
    private javax.swing.JTextArea searchWords;
    private javax.swing.JTabbedPane tabbedPane1;
    private javax.swing.JPanel upperP;
    // End of variables declaration//GEN-END:variables

    private void setNavigateButtonsState() {
        int curPage = page.getCurrentPageNo();
        if (curPage == 1) {  // first page
            firstButton.setEnabled(false);
            beforeButton.setEnabled(false);
            nextButton.setEnabled(true);
            lastButton.setEnabled(true);
        } else if (curPage == page.getPageCount()) { // last page
            firstButton.setEnabled(true);
            beforeButton.setEnabled(true);
            nextButton.setEnabled(false);
            lastButton.setEnabled(false);
        } else {
            firstButton.setEnabled(true);
            beforeButton.setEnabled(true);
            nextButton.setEnabled(true);
            lastButton.setEnabled(true);
        }
    }
    
    private void setNavigateButtonsDisable() {
        firstButton.setEnabled(false);
        beforeButton.setEnabled(false);
        nextButton.setEnabled(false);
        lastButton.setEnabled(false);
    }
}
