/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package compliance;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author hohkim
 */
public class Starter extends javax.swing.JFrame {

    /**
     * Creates new form Starter
     */
    public Starter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        collectorButton = new javax.swing.JButton();
        searcherButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        exitMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        collectorMenuItem = new javax.swing.JMenuItem();
        searcherMenuItem = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Auditor's Companion for Korean Air");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Auditor's Companion");

        collectorButton.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        collectorButton.setText("파일수집 및 인덱스 만들기");
        collectorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                collectorButtonActionPerformed(evt);
            }
        });

        searcherButton.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        searcherButton.setText("내용 검색");
        searcherButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searcherButtonActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        exitMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(exitMenuItem);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Work");

        collectorMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        collectorMenuItem.setText("파일수집 및 인덱싱");
        collectorMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                collectorMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(collectorMenuItem);

        searcherMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        searcherMenuItem.setText("내용 검색");
        searcherMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searcherMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(searcherMenuItem);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Help");

        aboutMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        aboutMenuItem.setText("About");
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });
        jMenu3.add(aboutMenuItem);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(collectorButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(searcherButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(collectorButton)
                .addGap(18, 18, 18)
                .addComponent(searcherButton)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void collectorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_collectorButtonActionPerformed
        // TODO add your handling code here:
        try {
            Collector collector = new Collector();
            Image icon = Toolkit.getDefaultToolkit().getImage(getClass()
                    .getResource("/compliance/images/search1.jpg"));
            collector.setIconImage(icon);
            collector.setTitle("Field Audiot's Companion for Korean Air");
            collector.setVisible(true);
            //new Collector().setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(Collector.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_collectorButtonActionPerformed

    private void searcherButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searcherButtonActionPerformed
        // TODO add your handling code here:
        Searcher searcher = new Searcher();
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass()
                .getResource("/compliance/images/search1.jpg"));
        searcher.setIconImage(icon);
        searcher.initResultTable();
        searcher.setVisible(true);
    }//GEN-LAST:event_searcherButtonActionPerformed

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Field Audtor's Companion for Korean Air\n"
                    + "- 파일 수집, 인덱스 달기, 자연어 검색 기능\n"
                    + "- Developed by H.H.Kim (SELBI)\n- Ver 1.0 (2012.11)");
    }//GEN-LAST:event_aboutMenuItemActionPerformed

    private void collectorMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_collectorMenuItemActionPerformed
        // TODO add your handling code here:
        collectorButtonActionPerformed(evt);
    }//GEN-LAST:event_collectorMenuItemActionPerformed

    private void searcherMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searcherMenuItemActionPerformed
        // TODO add your handling code here:
        searcherButtonActionPerformed(evt);
    }//GEN-LAST:event_searcherMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Starter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Starter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Starter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Starter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Starter starter = new Starter();
                Image icon = Toolkit.getDefaultToolkit().getImage(getClass()
                        .getResource("/compliance/images/search1.jpg"));
                starter.setIconImage(icon);
                //new Starter().setVisible(true);
                Dimension frameSize = starter.getSize();
                Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
                starter.setLocation((screenSize.width-frameSize.width)/2,
                        (screenSize.height-frameSize.height)/2);
                starter.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JButton collectorButton;
    private javax.swing.JMenuItem collectorMenuItem;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JButton searcherButton;
    private javax.swing.JMenuItem searcherMenuItem;
    // End of variables declaration//GEN-END:variables
}
